### PR TITLE
Add Upper/Lower Limits, Auto-scale functionality, & Optimized co-ordinates for MaximizeGraphs

### PR DESCRIPTION
**Pull request by fragtion**
Addresses issues #46 and #47

Sorry for breaking this into several minor commits. I used the github web interface to edit files / transfer my changes, and got a bit muddled up, lol. Please use "Files changed" feature to do the overall differential analysis of changes

### CODE REVIEW

**Review by bp2008 — APPROVED** [review]
I will give this a try and see if I find any issues.  Thanks!

**Comment by bp2008** [comment]
There are some minor issues I have fixed:
* GUI text alignment issues  (as you are aware, PingTracer's gui is a cluttered mess so it was hardly noticeable!)
* Overflow exception can occur in the graph painting when upper and lower limits come out equal to each other.
* No way to turn off rendering of the limit text on the right side.
* Unsuitable default values for new settings.

And a few I want to fix still before publishing a new release:
* The "Mouse ms" readout is computed based on old logic, not new, so it is wrong.
* Your "fix" to the maximized graph sizing causes them to no longer appear in the exact position and size requested by command line arguments.  It is a pretty minor issue since I may be the only person who automatically starts pingtracer instances in predefined locations upon system startup.

**Comment by bp2008** [comment]
The changes from this PR are included in [release 1.19](https://github.com/bp2008/pingtracer/releases/tag/1.19) (heavily modified), along with some other bugfixes.  Thank you for this contribution.

**Comment by bp2008** [comment]
You had also made it hard (or impossible) to see the red line drawn when a ping times out, by making it super small, and I fixed it and then broke it again in version 1.19.  This is resolved in [Release 1.19.1](url) and the height of these red lines is now configurable in Tools > Options.

**Comment by fragtion** [comment]
Really nice work. The new features definitely extend the app's usability in a good way, and everything seems to be working perfectly. You identified and resolved a number of strange/fringe cases and anomalies I left behind - nice work and thank you.

One small thing I do notice is that it's possible to extend the lower limit beyond/lower than "0" (although nobody should really be doing this anyway - so who cares..? XD).  Also, "Classic mode" seems to be taking the limits into account when it probably shouldn't be - but, setting the lower limit to 0 and upper limit to something high like 1000, allows classic mode to operate as it usually would (by all appearances).  I do prefer the new modes though, for most of my use cases! 😄 Cheers 🍻

**Comment by bp2008** [comment]
> I do notice is that it's possible to extend the lower limit beyond/lower than "0" into negative territory

That was intentional because some people have expressed frustration at not being able to see "0" clearly.  This way they can elevate it as much as 10 pixels.

> Also, "Classic mode" seems to be taking the limits into account when it probably shouldn't be (at least not directly, if you know what I mean). Setting the lower limit to 0 and upper limit to something high like 1000, allows classic mode to operate as it usually would (by all appearances). So I doubt an urgent hotfix release is needed this time - In your hands :)

That change is also intentional.  The original zoom behavior enforced an upper limit of the "worse threshold" times 1.5, which if I am not mistaken would have been 300 - which is the new default value for the upper limit setting you added.  So the default behavior in PingTracer 1.19+ should pretty much match what it did before, but with more customization available.

> PS - Just another quick (somewhat unrelated) suggestion for a future release (is this worth making a whole issue for?): instead of saving config to a hardcoded filename AppData\Roaming\PingTracer\settings.cfg, it would be useful to save the cfg based on the exe name. So PingTracer1.exe would save PingTracer1.cfg ... OR (I suppose a more "sensible", and backwards compatible approach) the ability to launch with a custom config file (-config command line argument or such). I realise that there are command line arguments to cover most settings, but especially with the introduction of more configuration variables now (like these new limits), it makes less sense to have one config file for all hosts/scenarios. I may want higher limits for an international host, and at the same time ping something nearby (>100ms typical vs <10ms typical), and to reconfigure the gui each time is impractical. Allowing distinct configs per session in this way, will make automation a bit easier without (in my opinion) really making the app any much more complicated to use! 🙂

You can place a copy of settings.cfg into the same folder as PingTracer.exe and it will be accessed from there instead of from the shared directory.  Because of this, you can essentially fork your configuration by just putting the settings file in the folder with the exe and then copying the folder.

Also all of the settings in the main form should be tied to the hostnames you have entered, so that helps with wanting to run multiple instances simultaneously.  However if you do run multiple instances simultaneously using the same config file, they will overwrite each other's changes which is very frustrating.  Certainly an aspect that could be improved in the future.

**Pull request merged**
